### ISSUE TITLE
Abnormally large node size upon zooming in with scroll wheel 

### ISSUE THREAD

**Issue by ktamiola** [ayalpinkus/shinglejs#9]
Dear @ayalpinkus, thank you so much for developing this wonderful tool pack. There seems to be an issue the rendering of the nodes. When you zoom out and zoom in, the nodes are abnormally large.

**The issue**
![image](https://user-images.githubusercontent.com/7100577/44000366-eb4fc8fa-9e1e-11e8-9702-8c943cbb9e79.png)

**Steps to reproduce**
1. Completely zoom out from the demo graph at https://www.ayalpinkus.nl/shinglejs/
2. Interact with few nodes.
3. Zoom in all the way to the lowest level.

**Platform**
```
Google Chrome (OSX)
Version 68.0.3440.106 (Official Build) (64-bit)
```
Could you point where the issue in the code might be?

**Comment by ayalpinkus** [comment]
Hi Kamil,
first off, thank you for using shingle, and thank you for contacting me!

My wife and I worked on this, and when she saw your email, she said that this has been in there for a long time. I just hadn't seen it!

You are probably zooming in and out with the wheel on your mouse (I use a pen tablet and so I don't have that wheel). If you zoom with the slider at the top left of the map, you will notice that it doesn't happen. That's how I always zoom!

I inserted a mouse with wheel and delved into it. The zooming code works based off two systems, one written by me and one writen by Rene, so it's a kind of a complex situation at the moment.

I did find the problem, or at least a temporary workaround for you: in the code, useNonScalingStrokeForNodes is set to false by default, and I now set it to true, and you don't see that artefact anymore. That version is in Github now, and you can see it work on my website.

You may need to remove the cached data from my website, or open a new Firefox window in private mode so the browser downloads the new file shingle.js.

I put Rene on the cc: Rene, would you be willing and have the time to look at this?

I also made the nodes slightly bigger in the function calcNodeScale. I think we need to revisit the node scaling code a bit still, small nodes are almost too small to click on at the moment.

I want to also make this a Gephi plugin one day, so that people can just easily create a layout for a large graph and publish a viewer for it online.

Sorry for the mistake, and thank you for contacting us!!! Hope you like it, and let me know if we can be of help.
Ayal

**Comment by ktamiola** [comment]
Dear Ayal, thank you so much for this truly comprehensive answer and (importantly) an excellent piece of software. I will test the `useNonScalingStrokeForNodes` later on this evening.

Besides that I have thought of quite a few small, but I dare say important technical improvements to your code. To be more specific, about node styling (colors) and the JPEG rendering. I will test these locally, and if they do make sense, perhaps we could do a code pull?

**Comment by ktamiola** [comment]
Thank you so much for your invaluable input @ayalpinkus ! I confirm the issue is solved by setting `useNonScalingStrokeForNodes` variable.
